name: CI + CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: acallo21/devops-ml-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Flask import
        run: python -c "import flask; print('Flask OK')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t acallo21/devops-ml-app:$VERSION .
          docker tag acallo21/devops-ml-app:$VERSION acallo21/devops-ml-app:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push acallo21/devops-ml-app:$VERSION
          docker push acallo21/devops-ml-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull acallo21/devops-ml-app:latest

            docker stop app || true
            docker rm -f app || true

            docker run -d -p 5000:5000 \
              --restart unless-stopped \
              --name app \
                acallo21/devops-ml-app:latest

                 echo "Waiting for app..."
            sleep 10

            curl -f http://localhost:5000 || exit 1