name: CI + CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Verify pytest
        run: python -m pytest --version

      - name: Run Tests
        run: python -m pytest -v


  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t acallo21/devops-ml-app:$VERSION .
          docker tag acallo21/devops-ml-app:$VERSION acallo21/devops-ml-app:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push acallo21/devops-ml-app:$VERSION
          docker push acallo21/devops-ml-app:latest

      - name: Validate Container Health
        run: |
          set -e
          docker run -d --name test-container -p 5000:5000 acallo21/devops-ml-app:$VERSION
          sleep 10
          curl -f http://localhost:5000/health
          docker rm -f test-container


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 (Docker Compose)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker compose pull
            docker compose up -d

            sleep 10

            curl -f http://localhost/health
            curl -f http://localhost/